### ISSUE TITLE
can react components be block level?

### ISSUE THREAD

**Issue by modosc** [jerolimov/react-showdown#12]
i'm running into issues where my components end up wrapped in a `<p>` which isn't valid for other block-level components (specifically `<div>`)

would it make sense to explicitly mark any components passed in as block-level? or have a separate option for such components? not really sure the best way to specify what should be block-level, but to actually do this we'd just need to do something like this for all of our `components`:

https://github.com/showdownjs/showdown/blob/master/src/subParsers/hashHTMLBlocks.js

and add it as a listener to `paragraphs.before`.

**Comment by andrewn** [comment]
I've just had this issue. I want to implement a `<Figure>` component that does some responsive image magic and render a native HTML `<figure>` tag.

`<figure>` is block-level so causes a React error when rendered in a `<p>`. I'm using @modosc's branch `modosc/react-showdown#block-level` which fixes this perfectly!

Would be great if #13 was merged.

_P.S. Really loving react-showdown, thanks!_

**Comment by modosc** [comment]
@jerolimov ping? any chance to get this in (or is there anything i can change to make it more palatable)?

**Comment by jerolimov** [comment]
Hi @modosc @andrewn, thanks for opening this issue and sorry for the long delay of communication.

I just rewrite the library in TypeScript and upgrade all dependencies. If you still use this library, please try the new version with the next tag.

`npm install --save react-showdown@next`

I keep this issue open to check if I could add this feature request in the next version. The first version of the reimplementation 2.0 is just a rewrite and should be compatible with the 1.x version.

**Comment by jerolimov** [comment]
Because this issue is years old, I close it until another user has issues with this.

One solution could be that you wrap your component with the surrounding elements in html:

```jsx
<p>
  Content...
  <CustomFigure />
  More content...
</p>
```

On the other side I'm open for any PR in the new TypeScript code base.

Thank you anyway for your feedback.
