### ISSUE TITLE
DOM element as Component breaks if style is present

### ISSUE THREAD

**Issue by ottosichert** [jerolimov/react-showdown#14]
There are several Markdown elements which will apply styles in Showdown, e.g. aligned table headers. When react-showdown renders this element with a custom component, it will break:

```js
import React, { Component } from "react";
import ReactDOM from "react-dom";
import { Markdown } from "react-showdown";

const text = `\
| a | b |
|:--|---|
| 1 | 2 |
`;

class Th extends Component {
  render() {
    return <th {...this.props} />;
  }
}

ReactDOM.render(
  <Markdown markup={text} components={{ th: Th }} tables />,
  document.getElementById("react-app")
);
```

<details>
  <summary><code>Uncaught TypeError: c.setAttribute is not a function</code></summary>

    at element.attribs.ref (Converter.js:53)
    at commitAttachRef (react-dom.development.js:11579)
    at commitAllLifeCycles (react-dom.development.js:12301)
    at HTMLUnknownElement.callCallback (react-dom.development.js:1299)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:1338)
    at invokeGuardedCallback (react-dom.development.js:1195)
    at commitAllWork (react-dom.development.js:12415)
    at workLoop (react-dom.development.js:12687)
    at HTMLUnknownElement.callCallback (react-dom.development.js:1299)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:1338)
</details>

<br />

Following lines are causing this, because the ref is not a DOM element:

https://github.com/jerolimov/react-showdown/blob/53ba6b1edbb1d4cb7e47a30726826180b9d2488f/lib/Converter.js#L44-L56

**Comment by jerolimov** [comment]
Hi @ottosichert, thanks for opening this issue and sorry for the long delay of communication.

I just rewrite the library in TypeScript and upgrade all dependencies. If you still use this library, please try the new version with the next tag.

`npm install --save react-showdown@next`

I keep this issue open to check if I could add this feature request in the next version. The first version of the reimplementation 2.0 is just a rewrite and should be compatible with the 1.x version.

**Comment by jerolimov** [comment]
The new version (2.0.2) supports now also inline styles. This inline styles solves also the problem with aligned table columns. Please try the new preview version:

`npm install --save react-showdown@next`

I will publish this as general available this week. I close this issue until there is new feedback for the new version.
