### ISSUE TITLE
Add displayName: 'MarkDown'

### ISSUE THREAD

**Issue by Steffan-Ennis** [jerolimov/react-showdown#16]
Add displayName to Element.js for react debug tools

```
module.exports = createClass({
	displayName: 'MarkDown',
	propTypes: {
		markdown: PropTypes.string,
		components: PropTypes.objectOf(PropTypes.oneOfType([
			PropTypes.element,
			PropTypes.func
		]))
	},

	render: function() {
		var markdown = this.props.markdown || this.props.markup;
		return new Converter(this.props).convert(markdown);
	},

	converter: Converter
});
```

**Comment by jerolimov** [comment]
Hi @Steffan-Ennis , thanks for open this issue and sorry for the long delay of communication.

I just rewrite the library in TypeScript and upgrade all dependencies. The time of createClass is long time ago and the new version supports a displayName and the React Dev Tools.

If you still use this library, please try the new version with the next tag.

`npm install --save react-showdown@next`
