### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by ottosichert** [jerolimov/react-showdown#17]
Showdown released some new important features and its dependency is currently at `"showdown": "^1.5.0"`.

**Comment by jerolimov** [comment]
Hi, thanks for open this issue and sorry for the long delay of communication.

I just released a new preview version of this lib.

The new version 2.0.0 uses showdown 1.9.1. If you still use this library, please try the new version with the next tag.

`npm install --save react-showdown@next`
