### ISSUE TITLE
Can i set a flavor?

### ISSUE THREAD

**Issue by cbarraford** [jerolimov/react-showdown#19]
Is there a means to set my [flavor](https://github.com/showdownjs/showdown#flavors)?

**Comment by psybork** [comment]
I've got the same question...

**Comment by psybork** [comment]
I've added the flavor option and setFlavor method to my fork, you can check it out @cbarraford  :smile:

**Comment by psybork** [comment]
@cbarraford, if you're still interested, you can use the fork I've created, just pass along the converter options and then call `converter.setFlavor('github')`, for example

**Comment by jerolimov** [comment]
Hi @cbarraford @dmorais92 , thanks for open this issue and sorry for the long delay of communication.

I just rewrite the library in TypeScript and upgrade all dependencies. The new version of this library supports the "flavor" option as well. If you still use this library, please try the new version with the next tag.

`npm install --save react-showdown@next`

After that you can set the flavor as prop.

```jsx
<Markdown flavor="github" markdown={yourContent.markdown} />
```

or


```jsx
<Markdown flavor={yourContent.flavor} markdown={yourContent.markdown} />
```

I removed the Converter export in the new version. Do you still require this internal part of the library or could you use the Markdown JSX tag instead?

I close this issue for now but I'm open for your feedback.
