### ISSUE TITLE
Extensions not working

### ISSUE THREAD

**Issue by simonelnahas** [jerolimov/react-showdown#47]
How is it possible to pass an extension for the converter, when it is created inside the package file `Converter.js`  like this:

 `this._converter = new showdown.Converter(options);`

**Comment by jerolimov** [comment]
Hi @simonelnahas, thanks for open this issue/question and sorry for the long delay of communication.

I just rewrite the library in TypeScript and upgrade all dependencies. If you still use this library, please try the new version with the next tag.

`npm install --save react-showdown@next`

You can add an extension in the new version by adding an extension prop.

```jsx

export default function App() {
  const markdown = '# Welcome to React Showdown!';

  // :ShowdownExtension is TypeScript and should be removed if you use JavaScript
  const myOutputExtension: ShowdownExtension = {
    type: 'output',
    regex: new RegExp(`<h1(.*)>`, 'g'),
    replace: `<h1 class="big" $1>`,
  };

  const myLanguageExtension: ShowdownExtension = {
    type: 'lang',
    regex: /Showdown/,
    replace: 'Markdown',
  };

  return (
    <MarkdownView
      markdown={markdown}
      extensions={[ myOutputExtension, myLanguageExtension ]}
    />
  );
};
```

I close this issue and hope this helps. I will extend the README later. If you have any other question please re-open this issue or create a new one.

Thanks
