### ISSUE TITLE
Image tags seems to trigger react error

### ISSUE THREAD

**Issue by julien51** [jerolimov/react-showdown#52]
Hello!

Thanks for your hard work and this new release!

I am adding an image to Markdown element using
```
![](https://cdn.pixabay.com/photo/2015/12/01/20/28/road-1072823_1280.jpg)
```

And React is throwing errors:

```
Error: img is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.
```

**Comment by jerolimov** [comment]
Hi @julien51 

thanks for finding and reporting this issue. I Just published a new version (2.0.3) which contains a fix for this! This issue happen with all "void element tags" like <img />, <hr /> or <input />

Thank you! Any other feedback is also welcome.
