### ISSUE TITLE
using self-closing components in the same line results in only the first one being added to the react tree

### ISSUE THREAD

**Issue by n1ru4l** [jerolimov/react-showdown#54]
CodeSandbox with reproduction:

https://codesandbox.io/s/epic-snow-6oz96?file=/src/App.js:417-482

Using two components in the same line result in only the first one being added to the react tree.
This is kind of a deal-breaker for inline `span` elements e.g. for multiple `Link` components that are inside a sentence.

With MDX this is possible (tested on https://mdxjs.com/playground).

I think it is related to self-closing tags. The following works as expected:

```
<CustomComponent name="world"></CustomComponent> <b a="lmao">lmao</b>
```

Using the `recognizeSelfClosing` option for `htmlparser` seems to resolve this issue (see https://github.com/jerolimov/react-showdown/pull/55/commits/50bfaef9ec97761ee3ed266c0d6bbc677f1291db).

**Comment by jerolimov** [comment]
@n1ru4l a new version 2.1.0 is released with all your changes! Thank for contributing
