### ISSUE TITLE
unable to style using className

### ISSUE THREAD

**Issue by OleksiiKachan** [jerolimov/react-showdown#64]
```
import MarkdownView from "react-showdown";

<MarkdownView markup="content here" className="some-class-name" />
```

renders to 
`<p>content here</p>`

so the component does not pass className to the` <p>` element

**Comment by GSoftwareDevelopment** [comment]
The 'className' attribute in the `<MarkdownView />` component defines the classes for the main block that is created by the component, i.e.:

If you are creating:

`<MarkdownView markup="content here" className="some-class-name" />`

This will result in:

```
<div class="some-class-name">
    <p>content here</p>
</div>
```

**Comment by jerolimov** [comment]
@OleksiiKachan does this solves your issue?

@GSoftwareDevelopment Thanks for answering the question :+1:
