### ISSUE TITLE
Declaration type is missing `className`

### ISSUE THREAD

**Issue by mlbonniec** [jerolimov/react-showdown#69]
Hi :) I'm using TypeScript and react-showdown, and I think the declaration type of the markdown props is missing `className` as props.
https://github.com/jerolimov/react-showdown/blob/c5a3d508ceb5130ca3ef7daf59e9b8c9145c11ae/src/MarkdownView.tsx#L18-L30
Am I wrong? Thanks :)

**Comment by jerolimov** [comment]
Hi @mlbonniec,

that's true. As workaround you can add a parent div with a className. When using `dangerouslySetInnerHTML` other props would be also ignored at the moment. See:

https://github.com/jerolimov/react-showdown/blob/master/src/MarkdownView.tsx#L132-L134

If you don't use `dangerouslySetInnerHTML` other props like `aria-...`, `data-...` and `className` / `style` should just work:

https://github.com/jerolimov/react-showdown/blob/master/src/MarkdownView.tsx#L147

If you like you can try to open a PR and extend `MarkdownViewProps` from the props a div have? Wdyt?

Maybe its `React.DetailedHTMLProps<React.HTMLAttributes<HTMLDivElement>, HTMLDivElement>`?

Maybe its possible to use a type of construct "props of type `<div />`"?

**Comment by jerolimov** [comment]
Thanks @mlbonniec for this fix.

A new version is successfully published (react-showdown@2.3.1)
