### ISSUE TITLE
Unknown markdown when converting <ul>

### ISSUE THREAD

**Issue by shibran** [jerolimov/react-showdown#72]
Unknown markdown when converting unordered list

![image](https://user-images.githubusercontent.com/38600380/134419533-64f90adf-a7d5-4cfa-af93-5b59f3cf3bd1.png)

**Comment by jerolimov** [comment]
Hey @shibran,

can you please explain the issue a little bit more? Isn't the html comment (`<!-- -->`) part of your markdown? Are the two strings in your screenshot first the output HTML and then input markdown?

**Comment by jerolimov** [comment]
If you still have an issue with here please provide a full example. Thanks
