### ISSUE TITLE
Prevent replace extension from lowercasing "html" tags?

### ISSUE THREAD

**Issue by alejoar** [jerolimov/react-showdown#73]
For example, I want to replace `img` tags with a React component. Say `StaticImage`.  For that I have an extension like this:

```
export const staticImageExtension = {
  type: "output",
  regex: new RegExp(
    `<img (.*?)>`,
    "g"
  ),
  replace: `<StaticImage $1/>`,
};
```
This effectively converts this
```
<img src="https://example.com/image.png">
```
into this
```
<staticimage src="https://example.com/image.png"></staticimage>
```

Emphasis on `staticimage`. Lower case. I need this to be `StaticImage` as in my replace regex. How can I achieve this?

**Comment by alejoar** [comment]
Digging deeper, I now realize it is React that is lower casing my component name and not Showdown. Still looking for a solution though.

**Comment by alejoar** [comment]
Ok, digging even deeper, this is related to another issue with the specific framework I'm using (Gatsby). I'm closing this issue, sorry!

**Comment by jerolimov** [comment]
All fine, thanks for letting me know and closing this again. Good luck.
