### ISSUE TITLE
How to add a wrapper for images?

### ISSUE THREAD

**Issue by ttcqaq** [jerolimov/react-showdown#74]
For the markdown text '\!\[\](example.jpg)', react-showdown can convert it to `img` tag. \<img src='example.jpg' \/\>
Is there any way to add a lazyload wrapper (such as react-lazyload), for example \<Lazyload\>\</Lazyload\> to the image?

\<Lazyload\>
    \<img src='example.jpg' \/\>
\</Lazyload\>

**Comment by antct** [comment]
> @antct sorry for the ping, but did you solved that ?

Yes, here is my pseudo code.

```typescript

import MarkdownView from 'react-showdown'
import LazyLoad from 'react-lazyload'

const CustomImageComponent = ({ src }: { src: string }) => {
  return (
    <LazyLoad
      height={200}
      offset={200}
      once
    >
        <div>
          <img
            src={src}
          />
        </div>
    </LazyLoad>
  )
}

const Markdown = (content: string) => {
  return <MarkdownView
    markdown={content}
    options={{ tables: true, emoji: true }}
    components={{ CustomImageComponent }}
  />
}

Markdown(`<CustomImageComponent src="IMAGE_URL" />`)
```

**Comment by tthsympa** [comment]
Yes ok, I did the same way... should be cool to detect "![]()" and return a custom component instead
